## Assignment 1<br>BUSI 520: Python for Business Research<br>Jones Graduate School of Business<br>Rice University<br>

1. Create a function that takes the lengths of two sides of a right triangle as inputs and returns the length of the hypotenuse.
2.  
    a. Create a list of names.  Using list enumeration, print the names in the form
    ```{verbatim}
        1. Adam
        2. Bob
        3. ...
    ```
    b.  Create a function that takes a list of strings as an input and prints the list as in part (a).
    c. Create a function that takes a list of strings as its input and returns a dictionary with integers 1, 2, ... as keys and the strings as values.
3. Create a list of numbers from 1 to 10.
    a. Write a loop to print only even numbers from the list.
    b. Write another loop to calculate and print the factorial of each number in the list.
4.  Write a loop to halve a given number until the result is less than 1.0e-6.
5. Create a function is_palindrome to check if a string is a palindrome (reads the same forwards as backwards -- e.g., 'radar' is a palindrome).  The function should return True if the input is a palindrome and False otherwise.
6. Write a script (.py file) that prompts the user to input

    a. title
    b. author
    c. journal
    d. volume
    e. pages
    f. year
    g. keyword
    h. pathname of a .bib file

    The function should then append a bibtex entry to the end of the .bib file formatted as follows, where the items within braces are the user's inputs.
  
```{verbatim}
    @article{keyword,
    title={title},
    author={author names},
    journal={journal name},
    volume={volume number},
    pages={pages},
    year={year},
    }
```

7. Write a script that, when executed in a directory, deletes all files in the directory whose extensions are not in ['.tex', '.pdf'].
